# Generated by Django 2.1.7 on 2019-03-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='laoshi')),
                ('age', models.IntegerField(max_length=20, verbose_name='age')),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
